export const Products = [
    {
        id: 1,
        img: '/keyBoard_1.png',
        title: 'LogiTech Keys',
        description: 'Lorem ipsum dolor sit amet consectetur. Lacinia venenatis nunc nulla enim nulla vel pulvinar metus. Lorem ipsum dolor sit amet consectetur.Lorem ipsum dolor sit amet consectetur.Lacinia venenatis nunc nulla enim nulla vel pulvinar metus.',
        type: 'KeyBoard',
        price: 'R$ 229,90',
        oldPrice: '329,90',
        type_catalogo: true,
        img_catalogo: '/teclado_catalogo.png',
        title_catalogo: 'Teclados',
        link_catalogo: '/pages/keyBoard',
        quantidade: 22,
        newOrOld: 'novo'
    },
    {
        id: 2,
        img: '/keyBoard_2.png',
        title: 'Mix Keys Mins',
        description: 'Lorem ipsum dolor sit amet consectetur. Lacinia venenatis nunc nulla enim nulla vel pulvinar metus. Lorem ipsum dolor sit amet consectetur.Lorem ipsum dolor sit amet consectetur.Lacinia venenatis nunc nulla enim nulla vel pulvinar metus.',
        type: 'KeyBoard',
        price: 'R$ 231,22',
        oldPrice: '331,90',
        type_catalogo: true,
        img_catalogo: '/mouse_catalogo_1.png',
        title_catalogo: 'Mouses',
        link_catalogo: '/pages/mouses',
        quantidade: 32,
        newOrOld: 'Usado'
    },
    {
        id: 3,
        img: '/keyBoard_3.png',
        title: 'Redragron Gamer',
        description: 'Lorem ipsum dolor sit amet consectetur. Lacinia venenatis nunc nulla enim nulla vel pulvinar metus. Lorem ipsum dolor sit amet consectetur.Lorem ipsum dolor sit amet consectetur.Lacinia venenatis nunc nulla enim nulla vel pulvinar metus.',
        type: 'KeyBoard',
        price: 'R$ 129,10',
        oldPrice: '219,90',
        type_catalogo: true,
        img_catalogo: '/monitor_catalogo_1.png',
        title_catalogo: 'Monitores',
        link_catalogo: '/pages/monitores',
        quantidade: 8,
        newOrOld: 'novo'
    },
    {
        id: 4,
        img: '/keyBoard_4.png',
        title: 'TH83',
        description: 'Lorem ipsum dolor sit amet consectetur. Lacinia venenatis nunc nulla enim nulla vel pulvinar metus. Lorem ipsum dolor sit amet consectetur.Lorem ipsum dolor sit amet consectetur.Lacinia venenatis nunc nulla enim nulla vel pulvinar metus.',
        type: 'KeyBoard',
        price: 'R$ 449,80',
        oldPrice: '529,90',
        type_catalogo: true,
        img_catalogo: '/caixa_catalogo_1.png',
        title_catalogo: 'Spkears',
        link_catalogo: '/pages/spkears',
        quantidade: 45,
        newOrOld: 'novo'
    },
    {
        id: 5,
        img: '/keyBoard_5.png',
        title: 'TH83',
        description: 'Lorem ipsum dolor sit amet consectetur. Lacinia venenatis nunc nulla enim nulla vel pulvinar metus. Lorem ipsum dolor sit amet consectetur.Lorem ipsum dolor sit amet consectetur.Lacinia venenatis nunc nulla enim nulla vel pulvinar metus.',
        type: 'KeyBoard',
        price: 'R$ 449,80',
        oldPrice: '529,90',
        type_catalogo: true,
        img_catalogo: '/mouse_pad_catalogo_1.png',
        title_catalogo: 'Mouse pads',
        link_catalogo: '/pages/mousePads',
        quantidade: 63,
        newOrOld: 'novo'
    },
    {
        id: 6,
        img: '/keyBoard_6.png',
        title: 'TH83',
        description: 'Lorem ipsum dolor sit amet consectetur. Lacinia venenatis nunc nulla enim nulla vel pulvinar metus. Lorem ipsum dolor sit amet consectetur.Lorem ipsum dolor sit amet consectetur.Lacinia venenatis nunc nulla enim nulla vel pulvinar metus.',
        type: 'KeyBoard',
        price: 'R$ 449,80',
        oldPrice: '529,90',
        type_catalogo: true,
        img_catalogo: '/phone_banner.png',
        title_catalogo: 'Fones',
        link_catalogo: '/pages/fones',
        quantidade: 54,
        newOrOld: 'Usado'
    },
    {
        id: 7,
        img: '/mouse_1.png',
        title: 'Linux cc',
        description: 'Lorem ipsum dolor sit amet consectetur. Lacinia venenatis nunc nulla enim nulla vel pulvinar metus. Lorem ipsum dolor sit amet consectetur.Lorem ipsum dolor sit amet consectetur.Lacinia venenatis nunc nulla enim nulla vel pulvinar metus.',
        type: 'Mouse',
        price: 'R$ 279.90',
        oldPrice: '829,90',
        quantidade: 97,
        newOrOld: 'Usado'
    },
    {
        id: 8,
        img: '/mouse_2.png',
        title: 'HyperXCloud',
        description: 'Lorem ipsum dolor sit amet consectetur. Lacinia venenatis nunc nulla enim nulla vel pulvinar metus. Lorem ipsum dolor sit amet consectetur.Lorem ipsum dolor sit amet consectetur.Lacinia venenatis nunc nulla enim nulla vel pulvinar metus.',
        type: 'Mouse',
        price: 'R$ 229,90',
        oldPrice: '329,90',
        quantidade: 41,
        newOrOld: 'Usado'
    },
    {
        id: 9,
        img: '/mouse_3.png',
        title: 'Mouse Pro Max',
        description: 'Lorem ipsum dolor sit amet consectetur. Lacinia venenatis nunc nulla enim nulla vel pulvinar metus. Lorem ipsum dolor sit amet consectetur.Lorem ipsum dolor sit amet consectetur.Lacinia venenatis nunc nulla enim nulla vel pulvinar metus.',
        type: 'Mouse',
        price: 'R$ 180,71,',
        oldPrice: '289,90',
        quantidade: 62,
        newOrOld: 'novo'
    },
    {
        id: 10,
        img: '/mouse_4.png',
        title: 'Mouse S23 Plus',
        description: 'Lorem ipsum dolor sit amet consectetur. Lacinia venenatis nunc nulla enim nulla vel pulvinar metus. Lorem ipsum dolor sit amet consectetur.Lorem ipsum dolor sit amet consectetur.Lacinia venenatis nunc nulla enim nulla vel pulvinar metus.',
        type: 'Mouse',
        price: 'R$ 890,12',
        oldPrice: '1029,90',
        quantidade: 26,
        newOrOld: 'novo'
    },
    {
        id: 11,
        img: '/mouse_5.png',
        title: 'Xr 2017',
        description: 'Lorem ipsum dolor sit amet consectetur. Lacinia venenatis nunc nulla enim nulla vel pulvinar metus. Lorem ipsum dolor sit amet consectetur.Lorem ipsum dolor sit amet consectetur.Lacinia venenatis nunc nulla enim nulla vel pulvinar metus.',
        type: 'Mouse',
        price: 'R$ 1500,12',
        oldPrice: '1929,90',
        quantidade: 33,
        newOrOld: 'novo'
    },
    {
        id: 12,
        img: '/mouse_6.png',
        title: '11 2018',
        description: 'Lorem ipsum dolor sit amet consectetur. Lacinia venenatis nunc nulla enim nulla vel pulvinar metus. Lorem ipsum dolor sit amet consectetur.Lorem ipsum dolor sit amet consectetur.Lacinia venenatis nunc nulla enim nulla vel pulvinar metus.',
        type: 'Mouse',
        price: 'R$ 1200,12',
        oldPrice: '1329,90',
        quantidade: 810,
        newOrOld: 'novo'
    },
    {
        id: 13,
        img: '/phone_1.png',
        title: 'H7',
        description: 'Lorem ipsum dolor sit amet consectetur. Lacinia venenatis nunc nulla enim nulla vel pulvinar metus. Lorem ipsum dolor sit amet consectetur.Lorem ipsum dolor sit amet consectetur.Lacinia venenatis nunc nulla enim nulla vel pulvinar metus.',
        type: 'Phone',
        price: 'R$ 699,99',
        oldPrice: '899,90',
        quantidade: 2,
        newOrOld: 'novo'
    }
]
